### ISSUE TITLE
Only 100 items showing

### ISSUE THREAD

**Issue by knynkwl** [verbb/icon-picker#14]
### Description
We have 144 items in the icon folder but only the first 100 icons are showing.

### Additional info

- Plugin version: 1.0.7
- Craft version: 3.1.32.1

**Comment by knynkwl** [comment]
@engram-design  Any chance there is a solution to this?

**Comment by engram-design** [comment]
This is a config setting, with the default set to 100 for performance reasons. See https://verbb.io/craft-plugins/icon-picker/docs/get-started/configuration to change this value.

**Comment by knynkwl** [comment]
Ah shoot my bad, thanks!
