### ISSUE TITLE
Support for Craft SVG Function

### ISSUE THREAD

**Issue by richhayler** [verbb/icon-picker#15]
Would be cool if this plugin supported the Craft's SVG function (https://docs.craftcms.com/v3/dev/functions.html#svg)

What would be neat about this is that you could then attach class names to the root SVG element, e.g.

`{{ svg(entry.iconPickerField, class='lemon-icon') }}`

`{{ svg('lemon.svg', class='lemon-icon') }}`

**Comment by engram-design** [comment]
Not sure how feasible it is to 'add support' for it, but you should be able to use `{{ svg(entry.iconPickerField.icon, class='lemon-icon') }}`

If not, I can add a `path` attribute that you can feed into this Twig function

**Comment by engram-design** [comment]
Added in [1.0.8](https://github.com/verbb/icon-picker/releases/tag/1.0.8). You can use: `{{ svg(entry.iconPickerField.path, class='lemon-icon') }}`
