### ISSUE TITLE
Font face name variable is missing

### ISSUE THREAD

**Issue by fa6ian** [verbb/icon-picker#19]
I'm getting an Undefined Variable: name error when I visit an entry with an icon picker field type. If I hard code the font name in the Services.php file it all seems to work, but I was wondering what, if anything, I'm doing wrong.

`$this->_loadedFonts[] = [
     'type' => 'local',
     'name' => 'font-face-' . $name,
     'url' => $this->_getUrlForPath($file),
];`

**Comment by engram-design** [comment]
Should be fixed in [1.0.8](https://github.com/verbb/icon-picker/releases/tag/1.0.8)
