### ISSUE TITLE
Feature Request - multiple directories

### ISSUE THREAD

**Issue by CreateSean** [verbb/icon-picker#2]
### Description

In incon-picker.php I'd like to configure mulitple directories - this is what I tried, but I'm not a php dev so may be completely wrong in any case.

```
<?php

return [
    '*' => [
        'iconSetsPath' => [
          getenv('SITE_PATH') . '/public/svgicons/general/',
          getenv('SITE_PATH') . '/public/svgicons/tech/',
        ],
        'iconSetsUrl' => '/svgicons/general/',
    ]
];
```

Ideally in the field type each directory would be seperated perhaps by a hr 

### Steps to reproduce

1.
2.

### Additional info

- Plugin version: 1.0.0.1
- Craft version: 3.1.8

**Comment by michaelroper** [comment]
Hey @CreateSean , did you try pointing the path to just `iconSetsPath` to `/public/svgicons`? The plug will actually recognise that there are subfolders, and let you either restrict the field to a specific folder, or if you select the parent folder, it will divide the icons up by folder as well.. 
![image](https://user-images.githubusercontent.com/60287/53228802-496b5300-36bd-11e9-8c60-2f5fbe781821.png)

**Comment by engram-design** [comment]
@CreateSean As @michaelroper suggests, the correct scenario would be to use `/public/svgicons` as we'll include any folders in that directory as an 'icon set'.
