### ISSUE TITLE
Valet SSL error on CP field edit screens in 1.0.8

### ISSUE THREAD

**Issue by gregorterrill** [verbb/icon-picker#20]
### Description
After updating to 1.0.8, trying to edit _any_ fields in the CP (even ones that aren't Icon Picker fields) results in the following error:

`yii\base\ErrorException: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in .../app/vendor/verbb/icon-picker/src/services/IconSources.php:34`

Editing entries that use Icon Picker fields works fine and the front-end of the site works fine. It's just the field edit screens that are throwing the error.

This is in a local dev environment on Valet with a self-signed SSL cert using `valet secure`. I saw issue #7 and tried the solution there in case it was related, but I apparently didn't have curl-openssl installed in homebrew anyway, so there was nothing to uninstall.

Had to roll back to Icon Picker 1.0.7 to continue working on the site for now.

- Plugin version: 1.0.8
- Craft version: 3.2.10

**Comment by engram-design** [comment]
This should be fixed in [1.0.10](https://github.com/verbb/icon-picker/releases/tag/1.0.10)
