### ISSUE TITLE
[FR] Redactor Support

### ISSUE THREAD

**Issue by bymayo** [verbb/icon-picker#23]
It would be great it if this plugin also made it available to pick an icon from within a redactor field.

We have clients sometimes request to put icons in headings, or within paragraphs (Mainly using FontAwesome)

**Comment by engram-design** [comment]
Added in [1.1.0](https://github.com/verbb/icon-picker/releases/tag/1.1.0). See [docs](https://verbb.io/craft-plugins/icon-picker/docs/feature-tour/redactor)

**Comment by bymayo** [comment]
Amazing, this will make some clients happy!
