### ISSUE TITLE
GraphQL integration & adding remote icon sets

### ISSUE THREAD

**Issue by nickroberts** [verbb/icon-picker#24]
I'm trying to include the ionicons like in the [example](https://verbb.io/craft-plugins/icon-picker/docs/developers/icon-sources), but I am unsure as to where to add the code to do this.

Also, I'm using Craft has a headless CMS, and the icon is only returned as a string. Is there any way to have it return the object?

**Comment by nickroberts** [comment]
Ok. I got the remote icons to work, but I'm still getting the string back from the built-in GraphQL functionality. Is there any plans to have it return the object? Thanks!

**Comment by nickroberts** [comment]
I would really like to use this plugin for our Craft install, but since we are using it as a headless CMS, we would love for it to be able to implement the built-in GraphQL functionality. Thanks for the awesome plugin!

**Comment by engram-design** [comment]
Added in [1.1.0](https://github.com/verbb/icon-picker/releases/tag/1.1.0)
