### ISSUE TITLE
Font Awesome styles

### ISSUE THREAD

**Issue by bymayo** [verbb/icon-picker#26]
### Description

Because Font Awesome comes with different styles (Regular, Solid, Light, Brands, Duotone) it would be good if you could set which style you wanted to output, currently theres no way of specifying this in the CMS.

So this would then output the correct class e.g. `.fab` for brands or `.fal` for light etc.

So currently if you choose Facebook icon, it won't out put as the class for the icon needs to be `fab fa-facebook`.

**Comment by engram-design** [comment]
Are you using the built-in Remote Icon set, or using your own self-hosted Font Awesome packs?

**Comment by bymayo** [comment]
@engram-design Just the built in one (Which I think is also slightly outdated as lot of the new FA icons aren't in the list)

**Comment by engram-design** [comment]
Yeah, I'd been debating updating it, but they've also changed he mechanism of delivery for newer updates. I don't believe there'll be a free CDN for the icons, instead you'd need to create a hosted kit. Still thinking about this

**Comment by michtio** [comment]
@engram-design this is a must to have, some icons from the free set are prefixed with `fab` ( for the brands ) some are prefixed with `fas`, `fal`, `fab` or `far`

We just load them in through NPM the full package and build it accordingly, but it requires to build up your classes as `fab fa-facebook-f` or `fal fa-external-link-alt` which would be different than `far fa-external-link-alt`

I see that you could simply add a `prefix` value to be outputted as well

**Comment by engram-design** [comment]
Added better support for Font Awesome 5/6 in [2.0.0](https://github.com/verbb/icon-picker/releases/tag/2.0.0)
