### ISSUE TITLE
Illegal offset type

### ISSUE THREAD

**Issue by lastgiven** [verbb/icon-picker#27]
### Description
I upgraded to the latest version of the plugin today and I am now receiving an error on all my pages that uses this field. 

The error that I am getting is `Illegal offset type`. 

![image](https://user-images.githubusercontent.com/24249787/72216546-13c89600-352b-11ea-91f0-85344c4732c8.png)

### Steps to reproduce

1. Install the latest version of the plugin
2. Create an icon field
3. Go to the page that it has been added to and get this error.

### Additional info

- Plugin version: 1.1.0
- Craft version: 3.3.19

**Comment by engram-design** [comment]
Should be fixed in [1.1.1](https://github.com/verbb/icon-picker/releases/tag/1.1.1)
