### ISSUE TITLE
Icons not showing (on windows)

### ISSUE THREAD

**Issue by superpikar** [verbb/icon-picker#28]
### Description
I add 2 folder inside my `iconSets` root. When I select the icon picker the icon is not rendered properly. it render the wrong URL of the svg, see screenshot below.

My icon-picker config
```
    '*' => [
        'iconSetsPath' => CRAFT_BASE_PATH . '/web/icons/',
        'iconSetsUrl' => '/icons/',
        'maxIconsShown' => 200,
        'redactorFieldHandle' => '',
    ]
```
I'm not sure whether this issue happens on windows OS only?

### Screenshots
![image](https://user-images.githubusercontent.com/2832280/74101054-353b9280-4b68-11ea-9643-dfffcd9b7ed4.png)

### Steps to reproduce
1. download feather icons svg https://feathericons.com/
2. put into `/web/icons`
3. select icon from on entry form

### Additional info

- Plugin version: 1.1.1
- Craft version: 3.3.20.1
- OS: Windows 10
- LAMP: Laragon https://laragon.org/

**Comment by engram-design** [comment]
Fixed in [1.1.2](https://github.com/verbb/icon-picker/releases/tag/1.1.2)
