### ISSUE TITLE
Filename without the extension

### ISSUE THREAD

**Issue by CreateSean** [verbb/icon-picker#3]
### Description

I'd like to be able to output the file name without the extensions. So if I have an icon twitter.svg a tag that would output `twitter` would be great. 

is this possible?

### Steps to reproduce

1.
2.

### Additional info

- Plugin version:
- Craft version:

**Comment by engram-design** [comment]
You can use `{{ entry.iconPickerField.getIconName() }}` as of [1.0.1](https://github.com/verbb/icon-picker/releases/tag/1.0.1)
