### ISSUE TITLE
Show a "transparency"-style checkerboard pattern behind icon dropdown

### ISSUE THREAD

**Issue by proimage** [verbb/icon-picker#39]
**What are you trying to do?**
I've got a spritesheet with both black and white icons. The white ones look blank unless I hover over them.

**What's your proposed solution?**
If you add a checkered background pattern as the background of the icon field's dropdown menu, it would both show their transparency, and make white icons more visible.

**Additional context**
Might also be nice to be able to select if the base background color of the icon picker dropdown is white, light grey, medium grey, dark grey, or black. Then separately, the checkered BG could be overlaid on top of that base BG color.

**Comment by engram-design** [comment]
Yeah, good thinking. It's on my todo list to completely rewrite the icon picker with Vue so its much more UX-friendly. This will also help us with some performance issues and functionality. Plans are to include a dropdown and modal UI option.

I'll mark this as something to bundle in!

**Comment by engram-design** [comment]
While I haven't added the checkbox, we do enforce icons to be a certain colour now in [2.0.0](https://github.com/verbb/icon-picker/releases/tag/2.0.0)
