### ISSUE TITLE
Not working within SuperTable

### ISSUE THREAD

**Issue by jorisnoo** [verbb/icon-picker#40]
**Description**

When an Icon Picker field is included in a SuperTable, no icons are being shown.

**Additional info**
- Plugin version: 1.1.9
- Craft version: 3.5.4
- Multi-site: No

**Additional context**

The request to `admin/actions/icon-picker/icons/icons-for-field` is empty when the field id is within a SuperTable field.

**Comment by engram-design** [comment]
Have you cleared the icon caches for the field(s)? I would also try re-saving the Super Table field that contains the icon picker field.

Lastly, is this Super Table field within a Matrix field?

**Comment by jorisnoo** [comment]
Hi @engram-design, thanks for your reply. Re-saving the Super Table field did the trick! Thanks!
