### ISSUE TITLE
Matrix Field block disappears in use with super table

### ISSUE THREAD

**Issue by alanski66** [verbb/icon-picker#41]
**Description**
Using icon filed in supertable in a matrix field

**Steps to reproduce**
1. Create matrix block with super table 
2. Add icon picker to supertable row
3. Add content to entry
4. Go to matrix field editor and edit the available fonts for icon picker field in the supertable field
5. Go back to entry to edit - matirx block is gone. Direct access to filed ediotr in backend results in 404 - field not found 

**Additional info**
- Plugin version:1.19
- Craft version:3.5
- Multi-site: No

**Additional context**

**Comment by alanski66** [comment]
PS I can confirm that the field is removed from the database - thus destroying complex matrix block (ouch)

**Comment by engram-design** [comment]
Can you let me know your Super Table version? Also, are you on Craft 3.5.0, or later versions? That seems very odd behaviour coming from Icon Picker. This doesn't happen with any other fields?

**Comment by alanski66** [comment]
Supertable 2.6.2
Craft Pro 3.5.9
I think its a supertable issue now - as I tried a different iconpicker (Dolphiq?) in supertable field and editing this resulted in the same deletion of field...

**Comment by engram-design** [comment]
Interesting. I might close this and we can pick up the issue over at https://github.com/verbb/super-table/issues
