### ISSUE TITLE
Covid Icons Missing From Free Font Awesome Icon Sets

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [verbb/icon-picker#42]
It looks like the `Viruses` icon is missing from the Picker for FA 5. You can see the new icons described here:

https://fontawesome.com/changelog/latest

But I don't see those in the list:

![Screen Shot 2020-12-04 at 12 49 43 PM](https://user-images.githubusercontent.com/39201467/101208309-3a098f80-362f-11eb-9d17-c5970659f700.png)

**Steps to reproduce**
1. Setup a standard Icon Picker field
2. Search for `viruses` within that field and no results show up :(

**Additional info**
- Plugin version: Latest
- Craft version: Latest
- Multi-site: No

**Additional context**

I had a quick peak in `cms/vendor/verbb/icon-picker/src/services/IconSources.php` and at line `42` you have this:

https://use.fontawesome.com/releases/v5.7.2/css/all.css

Doing a quick search and there's no `viruses` icon in there. So perhaps that CSS file needs to reference an updated version or something? I found https://use.fontawesome.com/releases/v5.15.1/css/all.css and this file does have the Viruses icon in it.

Thank you all for your help and this plugin is quite the time saver!

**Comment by engram-design** [comment]
Yep, just needs an update to the latest version! Future versions (when FA 6 is released) we'll include a method of version-picking.

Updated in [1.1.10](https://github.com/verbb/icon-picker/releases/tag/1.1.10)

**Comment by DynamiteGoesBoom** [comment]
@engram-design Most excellent! We'll get this updated and thanks for the quick turn around on this. You guys are the best!!
