### ISSUE TITLE
When added as a custom field to Navigation, the popup is cropped by the nav item popup

### ISSUE THREAD

**Issue by proimage** [verbb/icon-picker#45]
**Description**
I've added an Icon Picker field to a [Navigation](https://github.com/verbb/navigation) navigation (🤪):

![image](https://user-images.githubusercontent.com/1027523/126062052-7a6415d7-bf6f-4389-b16d-74c54ee8b497.png)

However, the Icon Picker popup is hidden by the extents of the Navigation node popup:

![image](https://user-images.githubusercontent.com/1027523/126062061-d24e3d88-dd99-4500-ad93-a731b49ec248.png)

**Steps to reproduce**
1. Install both Navigation and Icon Picker plugins
2. Customize Icon Picker to point to a good-sized sprite-sheet or collection of icons.
3. Create a custom Icon Picker field
4. Create a Navigation navigation
5. Assign the icon field to the Navigation
6. Add a node to the navigation
7. Double-click the node to open its popup.
8. Click on the icon field at the bottom of the popup

**Additional info**
- Plugin version: Icon Picker 1.1.10, Navigation 1.4.19
- Craft version: 3.6.12
- Multi-site: No

**Comment by engram-design** [comment]
Similar to https://github.com/verbb/navigation/issues/209 although I just can't seem to reproduce it, even though I know a few people have this issue.

Can you provide your browser version and OS?

Looking into it.

**Comment by engram-design** [comment]
Fixed in [1.4.20](https://github.com/verbb/navigation/releases/tag/1.4.20)
