### ISSUE TITLE
Ability to search tags in icon sets

### ISSUE THREAD

**Issue by siebird** [verbb/icon-picker#46]
Some icon sets have tags associated with the icon for related search terms. This would be a nice alternative for vs. searching by filename. 

For example, [Health Icons](https://healthicons.org/) has a `meta-data.json` that has tags related data (example below). Feather Icons does something a little different: https://github.com/feathericons/feather#api-reference
```
[
 {
  "id": "war",
  "category": "vehicles",
  "path": "vehicles/war",
  "tags": [
   "Armored Vehicle",
   "Cannon",
   "Gun",
   "Military",
   "Tank",
   "dhis2:war"
  ],
  "title": "War"
 },
 ...
]
```

**Comment by engram-design** [comment]
Yep, this is on my long-term roadmap to address, somehow. The issue really is that so many icon sets define this differently, like Font Awesome do a similar thing. It's about how to store this information I need to work out.

In addition, only the filename for an icon is currently searched, for performance. We'll be improving that in the next major version to include metadata, through our own non-jQuery dropdown solution.

**Comment by siebird** [comment]
Good to hear! I'll be curious to see how you solve it.

**Comment by engram-design** [comment]
Added the ability to set metadata in [2.0.0](https://github.com/verbb/icon-picker/releases/tag/2.0.0) see [docs](https://verbb.io/craft-plugins/icon-picker/docs/feature-tour/icon-sets#metadata)
