### ISSUE TITLE
Icon path variable in settings will be replaced with the representing path

### ISSUE THREAD

**Issue by SanboKyo** [verbb/icon-picker#47]
After saving the icon path variable will be replaced with the representing path.

@assetsPath/icons > /path/to/icons

![Bildschirmfoto 2021-09-07 um 09 25 58](https://user-images.githubusercontent.com/26556339/132305919-f36f2f54-b1a9-4534-b02d-41255128eabf.jpg)

**Additional info**
- Plugin version: 1.1.10
- Craft version: 3.7.10

**Comment by engram-design** [comment]
Should be fixed in [1.1.11](https://github.com/verbb/icon-picker/releases/tag/1.1.11) - didn't realise this wasn't tagged in a release yet.

**Comment by SanboKyo** [comment]
Wow, thanks!
