### ISSUE TITLE
jQuery Errors Affecting Broad CP Functionality   

### ISSUE THREAD

**Issue by theskyfloor** [verbb/icon-picker#5]
### Description

TypeError: undefined is not an object (evaluating 'Craft.IconPicker.Cache = { stylesheets: [], fonts: [] }') in js console

### Steps to reproduce

1. Install Icon Picker, load up settings, error comes.
2. Can't render Neo fields, update the CP, clear caches, and a host of other functionality is broken until I disable Icon Picker.

### Additional info

- Plugin version: 1.0.1
- Craft version: Craft CMS 3.1.16

**Comment by engram-design** [comment]
Sorry about that - what I get for a middle-of-the-night release. Fixed in [1.0.2](https://github.com/verbb/icon-picker/releases/tag/1.0.2)
