### ISSUE TITLE
Font Awesome 6 Support

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [verbb/icon-picker#51]
Font Awesome 6 just came out. I mean like *literally* came out a few moments ago. I'd just like to put this on your team's radar.

Thanks for all your team does to make adding icons to our sites so easy!

**Comment by engram-design** [comment]
Yup, time to see what's changed!

**Comment by engram-design** [comment]
Added in [2.0.0](https://github.com/verbb/icon-picker/releases/tag/2.0.0)
