### ISSUE TITLE
Overflow is hidden in Neo (maybe Matrix too?)

### ISSUE THREAD

**Issue by theskyfloor** [verbb/icon-picker#6]
### Description

When the field is inside of a Neo block/tab it ends up being cut off.

### Steps to reproduce

1. Add to Neo block
2. Open dropdown

### Additional info

- Plugin version: Latest
- Craft version: Latest

<img width="607" alt="screen shot 2019-03-06 at 9 18 40 am" src="https://user-images.githubusercontent.com/8887839/53893750-6d4f6280-3ff4-11e9-9caa-16ce6316d90f.png">

**Comment by engram-design** [comment]
Fixed in [1.0.3](https://github.com/verbb/icon-picker/releases/tag/1.0.3)
