### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by dima-ogrenich** [verbb/icon-picker#61]
### Describe the bug

<img width="504" alt="image" src="https://user-images.githubusercontent.com/66615356/204835993-f55a93ae-90c2-467d-9f89-8a2d04fa974d.png">

### Steps to reproduce

I try to install the plugin from the plugin store or through the console and get an error.

### Craft CMS version

Craft Pro 4.3.3

### Plugin version

2.0.6

### Multi-site?

Yes

### Application Info
PHP version	8.0.25
OS version	Linux 4.18.0-348.20.1.lve.1.el7h.x86_64
Database driver & version	MySQL 10.6.11
Image driver & version	GD 8.0.25
Craft edition & version	Craft Pro 4.3.3
Yii version	2.0.46
Twig version	v3.4.3
Guzzle version	7.5.0

### Plugins
Bulk Edit	4.0.1
Button Box	4.1.0
Campaign	2.2.3
Category Groups Field	2.0.1
Code Field	4.0.3
Connect	4.0.1
Control Panel Body Classes	2.3.0
Control Panel CSS	2.5.0
Control Panel JS	2.5.0
Control Panel Nav	4.0.9
CP Clear Cache	1.3.0
CP Field Inspect	1.4.4
Craft Commerce	4.2.3
Default Dashboard	2.0.0
Domains WMD	1.0.0
Embedded Assets	3.1.0
Feed Me	5.0.4
Field Manager	3.0.4
Font Awesome for Redactor	2.0.2
Formie	2.0.18
GDPR Cookie Consent	4.0.4
Google Maps	4.2.5
Guide	3.2.1
MatrixMate	2.1.2
Minify	4.0.0-beta.2
Navigation	2.0.13
Notifier	0.10.0
Odds & Ends	4.1.0
Palette	3.0.2
Quick Field	2.0.2
Redactor	3.0.2
Redactor Custom Styles	4.0.2
Redactor Tweaks	3.0.0
Redirects	4.1.6
Relax	2.0.1
Rich Variables	4.0.0
Scraper	4.0.0
Section + Product Type	2.0.1
SEO	4.0.15
Similar	4.0.0
Site Switcher	2.3.0
Smith	2.0.0
Sprig	2.3.0
Super Table	3.0.5
TinyMCE Field	1.2.1
Typed link field	2.1.5
View Count	1.1.1
Vite	4.0.3
Vizy	2.0.9

**Comment by engram-design** [comment]
Fixed in [2.0.7](https://github.com/verbb/icon-picker/releases/tag/2.0.7)
