### ISSUE TITLE
icons in dropdown not scaling 

### ISSUE THREAD

**Issue by micahmorgan1** [verbb/icon-picker#64]
### Describe the bug

after upgrading to 2.0.8 from the 2.0 beta my icons in an svg icon folder are not scaling properly to the default "iconItemSize" of 32px.  They seem to be scaling to 64px which is the h/w specified in the icon svg files.  (futuro).    The effect is that the icons are cropped in the dropdown.  It was all working properly in the beta.  

### Steps to reproduce

1. setup an icon set with svg's that have h/w css properties set to 64px
2. setup an icon-picker field with defaults and assign to entry type
3. view the icon drop-downs

### Craft CMS version

8.1.3

### Plugin version

2.0.8

### Multi-site?

No

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early, change your `verbb/icon-picker` requirement in `composer.json` to:

```
"require": {
  "verbb/icon-picker": "dev-craft-4 as 2.0.8",
  "...": "..."
}
```

Then run `composer update`.

**Comment by micahmorgan1** [comment]
Thanks that worked
