### ISSUE TITLE
Redactor icon picker dropdown is not visible

### ISSUE THREAD

**Issue by kunz1412** [verbb/icon-picker#77]
### Describe the bug

Hi,
I have multiple redactor fields on one page. If I select an icon for the first time on any redactor field everything is working great. But If I am trying to select an icon on a different redactor field, the icon picker dropdown is not visible.
Can you please check this. Thanks! 

### Steps to reproduce

1. Create a page with multiple redactor fields
2. Select an icon on the first redactor field
3. Try to select an icon from a different redactor field

If i save the page after selecting the first icon, everything is working fine.

### Craft CMS version

4.4.2

### Plugin version

dev-craft-4 as 2.0.12

### Multi-site?

Yes

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early, change your `verbb/icon-picker` requirement in `composer.json` to:

```
"require": {
  "verbb/icon-picker": "dev-craft-4 as 2.0.12",
  "...": "..."
}
```

Then run `composer update`.

**Comment by kunz1412** [comment]
This is working fine. Thx for the quick fix!
