### ISSUE TITLE
Craft 5 Icon sets page 500 error

### ISSUE THREAD

**Issue by steveDL** [verbb/icon-picker#90]
### Describe the bug

When navigating to icon sets in settings I get a 500 Internal Server Error. 

### Steps to reproduce

1. Install craft 5 and Verbb Icon picker app
2. create config fix in config folder 
3. navigate to settings > icon sets

### Craft CMS version

5 beta

### Plugin version

3.0.0-beta.3

### Multi-site?

No

**Comment by engram-design** [comment]
Can you post the error with `devMode` enabled, or post your logs from `/storage/logs/icon-picker.log`?

I think this should be fixed for the next release. To get this early, run `composer require verbb/icon-picker:"dev-craft-5 as 3.0.0-beta.3"`.

**Comment by engram-design** [comment]
Fixed in [3.0.0](https://github.com/verbb/icon-picker/releases/tag/3.0.0)
