### ISSUE TITLE
Ability to set the icon field to appear on cards in Craft 5

### ISSUE THREAD

**Issue by terryupton** [verbb/icon-picker#92]
### What are you trying to do?

I would like to see the icon field being able to be used as a thumbnail on cards views within the new Craft 5 feature.
Currently this is possible as an asset field. So hoping this could be also achievable for icon fields.

**An icon field.**
<img width="519" alt="Screenshot 2024-05-26 at 11 53 03" src="https://github.com/verbb/icon-picker/assets/5698596/02b2c981-9cad-4109-810d-dfa19c26d5bf">

**A native image field.**
<img width="599" alt="Screenshot 2024-05-26 at 11 53 09" src="https://github.com/verbb/icon-picker/assets/5698596/a1ff0454-4e19-4a7b-b891-a62ffcc92ae0">

### What's your proposed solution?

Allow the field to be used as thumbnail so that the icon appears on the listing/card views within the CMS.

**Comment by terryupton** [comment]
Is this something you are considering @engram-design 
I have 2 existing projects and a new one pending that would really benefit from this feature.

**Comment by engram-design** [comment]
Yep, I'm just not up to speed on the element card preview functionality, but it's on my todo list.

**Comment by terryupton** [comment]
Hey @engram-design,
Sorry to 'bump' this but wondered if you had any timeframe or immediate plans for this feature?
It's a blocker from me using it at the moment.
I have used assets currently as so;
<img width="1488" alt="Screenshot 2024-09-05 at 14 41 57" src="https://github.com/user-attachments/assets/cca26bc8-867f-4633-aae5-761a3a911856">


But would prefer to use the icon field for various reasons. But I need this visualisation for the icons on the cards.

Thanks
Terry

**Comment by engram-design** [comment]
Starting work on this, but the only real tricky issue is that while single SVG's are pretty easy to handle, SVG Spritesheets, Web Fonts and remote sets like Font Awesome require additional resources, which would be nuts to load every single time for an element's preview/card.

Looking into options.

**Comment by engram-design** [comment]
Added for the next release. To get this early, run `composer require verbb/icon-picker:"dev-craft-5 as 3.0.0"`. 

Please note that unfortunately due to a limitation of us not recording the Icon Set an icon belonged to, and non SVG icons will need to be picked again in the Icon Picker field. They will then be able to be used in element preview/cards.

Singular SVGs however should be fine as-is, as they don't require any additional resources to render.

**Comment by engram-design** [comment]
Added in [3.0.1](https://github.com/verbb/icon-picker/releases/tag/3.0.1)
