### ISSUE TITLE
New icon additions not built into production environment sprite sheet

### ISSUE THREAD

**Issue by chrispinion** [verbb/icon-picker#96]
### Describe the bug

Hi there,

I'm having some trouble getting new icons added to an existing svg sprite file to render into the front end sprite sheet in my prod environment (the icons render in both local and staging environments). What's odd is they are visible in the CP field on production, but they are absent on the front end when inspecting the built svg tag with all of the defs.

**Steps we've taken:**
- cleared the icon picker cache
- cleared blitz cache
- regenerated the icon set caches
- re-deployed the icon set commit
- verified the icons are present in the source svg file on the server

I thought maybe it'd be an issue with the icons themselves (or something else obvious) but I'm not certain since they work fine in the other environments.

I can provide files, screenshots, or additional info by email if needed. Thanks! 

### Steps to reproduce

1. 
2. 

### Craft CMS version

4.11.5

### Plugin version

2.0.18

### Multi-site?

No

**Comment by engram-design** [comment]
Not sure if you use CloudFlare as part of Blitz, but if you are, it's worth clearing that. If you browse directly to that file in your browser, do you see your icons in the source of the SVG spritesheet file?

If they're visible in the control panel, I'd have to suspect some form of cache being the issue.

**Comment by chrispinion** [comment]
Thanks @engram-design — this was a static cache sticking around on the server side. I had them clear it and it's good now. Appreciate it.
