### ISSUE TITLE
Fix - Cors issue

### ISSUE THREAD

**Issue by FabioDiCeglie** [verbb/icon-picker#98]
### Question

Hey team,

I'm having this issue with some icons on my website ( not all of them ) 

```
Access to fetch at 'https://ka-p.fontawesome.com/releases/v6.7.1/svgs/light/fa.svg?token=d82eeb28ae' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Do you have any idea where this it is coming from? On my fontawesome I  don't have any restriction in domain whitelist for now.

My kit setting === to this: https://github.com/verbb/icon-picker/issues/97#issuecomment-2493868870

**Comment by FabioDiCeglie** [comment]
I also tried to update the package version to 3.0.2 connected to this issue #97 but I still have the same problem.

**Comment by engram-design** [comment]
When you mention on your website, is that on the front-end? If so, that's not something we control with Icon Picker. If you mean in the control panel, then that's indeed an Icon Picker issue. Just wanted to check first!

**Comment by FabioDiCeglie** [comment]
I mean the error is it showing in the front-end of course, but the main issue I think comes from the icon picker, because some others icons work perfectly. Or I am wrong?

**Comment by engram-design** [comment]
Icon Picker doesn’t do anything on your front-end, it really just stores the ID of the icon, and it’s up to you to load Font Awesome in whatever recommended way works for your front-end.
